import { useEffect, useState } from "react";
import {
  Copy,
  Check,
  RefreshCw,
  ExternalLink,
  FileText,
  Bot,
} from "lucide-react";

export default function AgentDiscovery() {
  const [report, setReport] = useState(null);
  const [copied, setCopied] = useState("");
  const [generating, setGenerating] = useState(false);

  useEffect(() => {
    const stored = localStorage.getItem("acr_latest_report");

    if (stored) {
      try {
        setReport(JSON.parse(stored));
      } catch (error) {
        console.error("Unable to parse audit report:", error);
      }
    }
  }, []);

  const agentDiscovery = report?.agent_discovery || {};

  const agentsMd =
    agentDiscovery.agents_md ||
    agentDiscovery.agentsMd ||
    "";

  const llmsTxt =
    agentDiscovery.llms_txt ||
    agentDiscovery.llmsTxt ||
    "";

  const llmsFullTxt =
    agentDiscovery.llms_full_txt ||
    agentDiscovery.llmsFullTxt ||
    "";

  const ucp =
    agentDiscovery.ucp ||
    agentDiscovery.ucp_config ||
    null;

  const copyText = async (key, value) => {
    if (!value) return;

    await navigator.clipboard.writeText(value);
    setCopied(key);

    setTimeout(() => {
      setCopied("");
    }, 2000);
  };

  const handleGenerate = async () => {
    setGenerating(true);

    // The current audit report is already generated by your backend.
    // Reload it from localStorage so the page reflects the latest audit.
    const stored = localStorage.getItem("acr_latest_report");

    if (stored) {
      try {
        setReport(JSON.parse(stored));
      } catch (error) {
        console.error(error);
      }
    }

    setTimeout(() => {
      setGenerating(false);
    }, 700);
  };

  const downloadText = (filename, content) => {
    if (!content) return;

    const blob = new Blob([content], {
      type: "text/plain;charset=utf-8",
    });

    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");

    a.href = url;
    a.download = filename;
    a.click();

    URL.revokeObjectURL(url);
  };

  const hasAgentData =
    agentsMd || llmsTxt || llmsFullTxt || ucp;

  return (
    <main className="min-h-screen bg-[var(--app-bg)] px-6 py-8">
      <div className="mx-auto max-w-7xl">

        {/* Header */}
        <div className="mb-8 flex items-start justify-between gap-4">
          <div>
            <div className="mb-2 flex items-center gap-2">
              <Bot
                size={24}
                className="text-[var(--app-green)]"
              />

              <h1 className="text-2xl font-bold text-[var(--app-text)]">
                Agent Discovery
              </h1>
            </div>

            <p className="max-w-2xl text-sm text-[var(--app-muted)]">
              Manage the machine-readable information that helps AI
              agents discover and understand your Shopify store.
            </p>
          </div>

          <button
            onClick={handleGenerate}
            disabled={generating}
            className="flex items-center gap-2 rounded-lg bg-[var(--app-green)] px-4 py-2.5 text-sm font-semibold text-white hover:bg-[var(--app-green-dark)] disabled:opacity-60"
          >
            <RefreshCw
              size={16}
              className={generating ? "animate-spin" : ""}
            />

            {generating ? "Refreshing..." : "Refresh"}
          </button>
        </div>

        {!report && (
          <div className="rounded-xl border border-[var(--app-border)] bg-white p-8 text-center">
            <FileText
              size={32}
              className="mx-auto mb-3 text-[var(--app-muted)]"
            />

            <h2 className="mb-2 text-lg font-semibold text-[var(--app-text)]">
              No audit report available
            </h2>

            <p className="text-sm text-[var(--app-muted)]">
              Run an audit from the Dashboard first. Agent discovery
              information will appear here when the audit completes.
            </p>
          </div>
        )}

        {report && !hasAgentData && (
          <div className="rounded-xl border border-[var(--app-border)] bg-white p-8">
            <h2 className="mb-2 text-lg font-semibold text-[var(--app-text)]">
              Agent discovery data is not available
            </h2>

            <p className="text-sm text-[var(--app-muted)]">
              The latest backend audit report does not contain
              agent discovery information.
            </p>
          </div>
        )}

        {report && hasAgentData && (
          <div className="space-y-6">

            {/* Overview cards */}
            <div className="grid gap-4 md:grid-cols-4">

              <StatusCard
                title="agents.md"
                available={Boolean(agentsMd)}
              />

              <StatusCard
                title="llms.txt"
                available={Boolean(llmsTxt)}
              />

              <StatusCard
                title="llms-full.txt"
                available={Boolean(llmsFullTxt)}
              />

              <StatusCard
                title="UCP"
                available={Boolean(ucp)}
              />

            </div>

            {/* agents.md */}
            <DiscoveryCard
              title="agents.md"
              description="Instructions and context for AI agents interacting with the store."
              content={agentsMd}
              copied={copied === "agents"}
              onCopy={() =>
                copyText("agents", agentsMd)
              }
              onDownload={() =>
                downloadText("agents.md", agentsMd)
              }
            />

            {/* llms.txt */}
            <DiscoveryCard
              title="llms.txt"
              description="Machine-readable store information intended for language models."
              content={llmsTxt}
              copied={copied === "llms"}
              onCopy={() =>
                copyText("llms", llmsTxt)
              }
              onDownload={() =>
                downloadText("llms.txt", llmsTxt)
              }
            />

            {/* llms-full.txt */}
            <DiscoveryCard
              title="llms-full.txt"
              description="Extended machine-readable information for AI systems."
              content={llmsFullTxt}
              copied={copied === "llms-full"}
              onCopy={() =>
                copyText("llms-full", llmsFullTxt)
              }
              onDownload={() =>
                downloadText(
                  "llms-full.txt",
                  llmsFullTxt
                )
              }
            />

            {/* UCP */}
            <div className="overflow-hidden rounded-xl border border-[var(--app-border)] bg-white">

              <div className="flex items-center justify-between border-b border-[var(--app-border)] px-5 py-4">

                <div>
                  <h2 className="font-semibold text-[var(--app-text)]">
                    Universal Commerce Protocol
                  </h2>

                  <p className="mt-1 text-sm text-[var(--app-muted)]">
                    Commerce configuration discovered from the latest audit.
                  </p>
                </div>

                {ucp && (
                  <span className="rounded-full bg-[var(--app-orange-light)] px-3 py-1 text-xs font-semibold text-[var(--app-green)]">
                    Available
                  </span>
                )}
              </div>

              <div className="p-5">

                {ucp ? (
                  <pre className="max-h-96 overflow-auto rounded-lg bg-[var(--acr-cream)] p-4 text-xs leading-6 text-[var(--acr-black)]">
                    {typeof ucp === "string"
                      ? ucp
                      : JSON.stringify(ucp, null, 2)}
                  </pre>
                ) : (
                  <p className="text-sm text-[var(--app-muted)]">
                    UCP information was not returned by the latest audit.
                  </p>
                )}

              </div>
            </div>

          </div>
        )}
      </div>
    </main>
  );
}

function StatusCard({ title, available }) {
  return (
    <div className="rounded-xl border border-[var(--app-border)] bg-white p-5">

      <div className="mb-3 flex items-center justify-between">
        <FileText
          size={20}
          className="text-[var(--app-green)]"
        />

        {available ? (
          <span className="flex items-center gap-1 rounded-full bg-[var(--app-orange-light)] px-2.5 py-1 text-xs font-semibold text-[var(--app-green)]">
            <Check size={13} />
            Available
          </span>
        ) : (
          <span className="rounded-full bg-gray-100 px-2.5 py-1 text-xs font-semibold text-gray-500">
            Not available
          </span>
        )}
      </div>

      <p className="font-semibold text-[var(--app-text)]">
        {title}
      </p>
    </div>
  );
}

function DiscoveryCard({
  title,
  description,
  content,
  copied,
  onCopy,
  onDownload,
}) {
  return (
    <div className="overflow-hidden rounded-xl border border-[var(--app-border)] bg-white">

      <div className="flex items-start justify-between gap-4 border-b border-[var(--app-border)] px-5 py-4">

        <div>
          <h2 className="font-semibold text-[var(--app-text)]">
            {title}
          </h2>

          <p className="mt-1 text-sm text-[var(--app-muted)]">
            {description}
          </p>
        </div>

        <div className="flex shrink-0 gap-2">

          <button
            onClick={onCopy}
            disabled={!content}
            className="flex items-center gap-1.5 rounded-lg border border-[var(--app-border)] px-3 py-2 text-xs font-semibold text-[var(--app-text)] hover:bg-[var(--acr-cream)] disabled:opacity-40"
          >
            {copied ? (
              <>
                <Check size={14} />
                Copied
              </>
            ) : (
              <>
                <Copy size={14} />
                Copy
              </>
            )}
          </button>

          <button
            onClick={onDownload}
            disabled={!content}
            className="flex items-center gap-1.5 rounded-lg border border-[var(--app-border)] px-3 py-2 text-xs font-semibold text-[var(--app-text)] hover:bg-[var(--acr-cream)] disabled:opacity-40"
          >
            <ExternalLink size={14} />
            Download
          </button>

        </div>
      </div>

      <div className="p-5">

        {content ? (
          <pre className="max-h-96 overflow-auto rounded-lg bg-[var(--acr-cream)] p-4 text-xs leading-6 text-[var(--acr-black)]">
            {content}
          </pre>
        ) : (
          <div className="rounded-lg bg-[var(--acr-cream)] p-6 text-center text-sm text-[var(--app-muted)]">
            No content returned by the latest audit.
          </div>
        )}

      </div>
    </div>
  );
}